# Generated by Django 3.2 on 2021-11-22 22:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('symbols', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('permalink', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('symbol_type', models.PositiveSmallIntegerField(choices=[(1, 'AAPL Symbol Type'), (2, 'TWTR Symbol Type'), (3, 'GOLD Symbol Type'), (4, 'INTC Symbol Type'), (999, 'Invalid Type')], default=999)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='AAPL',
        ),
        migrations.DeleteModel(
            name='GOLD',
        ),
        migrations.DeleteModel(
            name='INTC',
        ),
        migrations.DeleteModel(
            name='TWTR',
        ),
    ]
