# Generated by Django 3.2 on 2021-11-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbols', '0002_auto_20211122_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedrecord',
            name='url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
